name: unvired_sdk
description: A new Flutter package project.
version: 0.0.83 #Version
author: Unvired
homepage: https://unvired.com/

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  # sqflite_sqlcipher: 2.0.0
  logger:
#    git:
#      url: https://intranet.indience.in:8443/flutter/flutter_logger_package.git
#      ref: 0.0.83 #Logger Version
     path: ../logger
  http: ^0.13.3
  crypto: ^3.0.1
  connectivity_plus: ^2.3.2
  isolated_worker: ^0.0.1+1
  drift: ^2.3.0
  uuid: ^3.0.4
  hive: 2.1.0
  flutter_device_type: ^0.4.0
  enum_to_string: ^2.0.1
  hive_flutter: ^1.1.0
  package_info_plus: any
  meta: any
  archive: ^3.3.1
  aes_crypt_null_safe: 2.0.2
  sqlcipher_flutter_libs:
    git:
      url: https://github.com/simolus3/sqlite3.dart.git
      path: sqlcipher_flutter_libs
  msix: any
  # Helper to find the database path on mobile
  path_provider: ^2.0.15
  undo: ^1.4.0
  dart_ipify: ^1.0.2
  device_info_plus: any
  async_task: ^1.0.11
  executor: ^2.2.2
  base32: 2.1.1
  webviewx: ^0.2.1
  url_launcher: ^6.0.18
#  webview_windows: ^0.1.6

  firebase_messaging: ^14.1.0
  firebase_core: ^2.4.0
  xml2json: ^5.3.2
  # path_provider_android: ^2.0.12
  # path_provider_ios: ^2.0.8 
  connectivity_plus_windows: 1.2.2
  uni_links: ^0.5.1
  encrypt: ^5.0.1
  flutter_local_notifications: ^9.7.0
  rxdart: ^0.27.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.3.2
  build_runner: ^2.3.2
  build_web_compilers: ^3.2.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:

  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
  # vignesh
  #scripts
  #flutter pub run build_runner build --delete-conflicting-outputs
